### ISSUE TITLE
Speech recognition is convenience not a capability

### ISSUE THREAD

**Issue by petkaantonov** [NOtherDev/whatwebcando#12]
If you can access microphone you can do speech recognition.

**Comment by NOtherDev** [comment]
Well if you mean reading the `<audio>` stream, then sure, technically you can run the recognition yourself. I've found a library that is doing exactly this - [pocketsphinx.js](http://syl22-00.github.io/pocketsphinx.js/). Are there any other solutions you're thinking of? Let me know please and I'll put a note in the Speech Recognition page.

**Comment by petkaantonov** [comment]
I am not sure of the specifics but I imagine having microphone API yet inability to access the input from microphone would be pretty unreasonable. I guess MediaStream is can be used for this?

**Comment by NOtherDev** [comment]
Yes. Added an appropriate note in [Speech Recognition](https://whatwebcando.today/speech-recognition.html). Thanks!

**Comment by petkaantonov** [comment]
I still wonder if it should be mentioned that doing it yourself directly has some advantages as you have far more control over the algorithm and limitations. For example webkitSpeechRecognition seems to have a [maximum duration of 1 minute](https://stackoverflow.com/a/20961085/995876).
