### ISSUE TITLE
Add Origin Trials token for Web Bluetooth page

### ISSUE THREAD

**Issue by beaufortfrancois** [NOtherDev/whatwebcando#17]
With Web BLuetooth now available for Origin Trials, I would suggest adding an Origin Trial token to https://whatwebcando.today/bluetooth.html so that people don't have to enable the experimental flag to try our your demos.

See https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web#available-for-origin-trials

**Comment by NOtherDev** [comment]
Well, my demos are actually hosted on CodePen.io, so unless I move the demo directly to WhatWebCanDo, it's CodePen who would need to add Origin Trials, am I right?

**Comment by beaufortfrancois** [comment]
Yes you're right but you can ask for a OT token for https://s.codepen.io and simply include it in your HTML code.

**Comment by NOtherDev** [comment]
Done: https://s.codepen.io/WhatWebCanDo/debug/VvPaRY
Thanks @beaufortfrancois!
