### ISSUE TITLE
Web Bluetooth demo doesn't work on cross-origin iframes

### ISSUE THREAD

**Issue by beaufortfrancois** [NOtherDev/whatwebcando#18]
![screenshot 2016-08-10 at 2 59 12 pm](https://cloud.githubusercontent.com/assets/634478/17554420/02dc2892-5f0b-11e6-8435-67f33b85b22c.png)

**Comment by NOtherDev** [comment]
Yes, you're right. I've also spotted that recently: https://github.com/NOtherDev/whatwebcando/issues/16
I'll handle that soon. Thanks!

**Comment by NOtherDev** [comment]
Added an alert with a standalone mode link. Thanks!

**Comment by beaufortfrancois** [comment]
It would be nice to not show the warning message if you're in standalone mode:

```js
document.getElementById('alert').hidden = (window.self === window.top);
```

**Comment by NOtherDev** [comment]
That makes sense. Added, thank you again!
