### ISSUE TITLE
Clarification for Pointer Device Adaptation

### ISSUE THREAD

**Issue by patrickhlauke** [NOtherDev/whatwebcando#2]
Hey there, just wanted to point out a potential clarification needed for https://whatwebcando.today/pointer-adaptation.html

> depending on the way the user is interacting with the application.

> It allows identifying whether the pointer used ...

Note that it's not necessarily the way the user is interacting, or which actual pointer is being used, but the *primary* pointer. What constitutes a *primary* pointer? The spec does not specifiy this, and it's up to the user agent to determine this. Currently, browsers will simply default to whatever the "classic" input for the particular device would be. For instance, a browser on a mobile device would consider touchscreen to be the *primary* input device - regardless of whether the user has paired a bluetooth mouse with it and is actually using the mouse itself; on 2-in-1 devices, or traditional desktops with added touchscreen, browsers currently treat the mouse as *primary*, regardless of whether the user is actually interacting with the touchscreen. In short, the wording here needs some slight tweaking to reflect this and to avoid that devs get a false sense of security. I'd suggest something like

> depending on the primary input of the current device.

> It allows identifying whether the primary pointer ...

Also, it may be worth lumping the `any-pointer` and `any-hover` media features in here as well?

(I was going to point to https://dev.opera.com/articles/media-features/ ... but I see that you've actually got that in the resources already :) )

**Comment by NOtherDev** [comment]
Done, thanks!
https://whatwebcando.today/pointer-adaptation.html

**Comment by patrickhlauke** [comment]
:+1:
