### ISSUE TITLE
Update Web Bluetooth availability

### ISSUE THREAD

**Issue by beaufortfrancois** [NOtherDev/whatwebcando#20]
Web Bluetooth page says:

> Current support is limited to a partial and experimental (flag-disabled by default) implementation in Google Chrome 45.

However according to https://developers.google.com/web/updates/2015/07/interact-with-ble-devices-on-the-web,

> Web Bluetooth API is currently available to be enabled experimentally on your origin in Origin Trials, or locally on your machine using an experimental flag. The implementation is partially complete and currently available on Chrome OS, Chrome for Android M, Linux, and Mac.

Could we update and/or maybe link to this source as well?

Thanks in advance,
Francois.

**Comment by NOtherDev** [comment]
Added more info about OSes and Origin Trials. The link you've mentioned is already included in the Resources section.

Thanks again!
