### ISSUE TITLE
Update links for MediaRecorder and RTCPeerConnection codepens

### ISSUE THREAD

**Issue by miguelao** [NOtherDev/whatwebcando#26]
Could you please fork and add? Thanks.

- MediaRecorder pen: https://codepen.io/miguelao/pen/bZPKwP

- RTCPeerConnection https://codepen.io/miguelao/pen/RRXPEv

(both tested with FF and Cr)

**Comment by NOtherDev** [comment]
Thanks! Forked and deployed: https://whatwebcando.today/
