### ISSUE TITLE
"Taking photos" incorrectly shown as disabled after the UI update

### ISSUE THREAD

**Issue by dandv** [NOtherDev/whatwebcando#27]
"Taking photos" shows as a red X in the new UI, using the latest stable Chrome and Firefox on Android. With the same browsers, "Camera and microphone" had a checkmark a few days ago:

http://stackoverflow.com/questions/35504194/what-features-do-progressive-web-apps-have-vs-native-apps-and-vice-versa-on-an/39027789#39027789

**Comment by NOtherDev** [comment]
Well, you're mostly right. What was previously available under "Camera and microphone" is now "Basic streaming" and it's still available. "Taking photos" is a new entry specifically about ImageCapture API - and this API is not available yet. 

Taking pictures with `getUserMedia` only is more a workaround for the lack of "proper" image capturing API, with zoom controls etc. (and this is what ImageCapture promises). With `getUserMedia` we're actually only taking screenshots from the `<video>` element.

But I agree the "Basic streaming" label might be a bit mysterious and "Taking photos" with a red X might suggest there is no way to take pictures from the web. What if I rename "Basic streaming" to "Camera streams" and "Taking pictures" to "Advanced camera controls"?

**Comment by dandv** [comment]
Ah, that makes sense. (Incidentally, I'm working on a `takephoto()` polyfill.) I should've tapped on "Take photos" to see what it was about. This brings up the point that on mobile, it might not be discoverable that each feature can be tapped on for more information. On desktop, the hover style does that, but the the labels don't look like buttons or links.

> What if I rename "Basic streaming" to "Camera streams" and "Taking pictures" to "Advanced camera controls"?

:+1: for "Advanced camera controls". How about "Audio/video capture" instead of "Basic streaming"? To the less versed user, "streaming" might be associated with YouTube and Spotify rather than WebRTC.

**Comment by NOtherDev** [comment]
Renames already deployed. Thanks.

About the "clickability" issue - that's a good point. I didn't want to have the classic buttons there because it will look very messy with tons of buttons. I've introduced the small arrows right now - have a look and let me know if that's better.

**Comment by dandv** [comment]
<3 the arrows!

BTW, while playing with the Audio/Video capture and Recording samples, I noticed there's feedback in Chrome on OS X, but not in Chrome on Android.

**Comment by NOtherDev** [comment]
Hmm @dandv what do you mean by no feedback? I've just checked on my Chrome Dev 54 on Android 5.1 and all the A/V demos worked fine for me.

**Comment by dandv** [comment]
I mean [audio feedback](https://en.wikipedia.org/wiki/Audio_feedback). I think the issue is known, since https://webrtc.github.io/samples/src/content/getusermedia/gum/ warns "if you're not using headphones, pressing play will cause feedback".
