### ISSUE TITLE
It can do some more.

### ISSUE THREAD

**Issue by hemanth** [NOtherDev/whatwebcando#28]
Physical Web (Android)
Device Motion and Orientation (all)
Gamepad (all -ChromeOS)

**Comment by kenchris** [comment]
Web NFC is there already and some of the new generic sensors (not all yet)

**Comment by hemanth** [comment]
magnetometer, accelerometer, gyroscope, barometer, thermostat, hygrostat. right?

**Comment by kenchris** [comment]
barometer, thermostat, hygrostat spec are not public yet as they are not in the W3C working group charter, but we might make them unofficial drafts soon and then later recharter. This will be discussed at the yearly W3C TPAC meeting next week

**Comment by kenchris** [comment]
ambient light sensor as well

**Comment by NOtherDev** [comment]
More sensors will be described soon. By now there is [Proximity Sensor](https://whatwebcando.today/proximity.html), [Ambient Light Sensor](https://whatwebcando.today/ambient-light.html), [Accelerometer & Gyroscope](https://whatwebcando.today/accelerometer.html) described.

[Device Motion](https://whatwebcando.today/accelerometer.html) and [Device Orientation](https://whatwebcando.today/device-orientation.html) are already described, too.

Gamepad API looks interesting and has a decent support. Will take a look in the next series of updates.

For Physical Web, I'm not sure whether I should handle that. If I understand that thing correctly, it's a custom protocol implemented over Bluetooth LE and is not a part of any specification, am I correct? As such it can theoretically be handled by Bluetooth API manually and the actual capability is the Bluetooth support, that is [already described](https://whatwebcando.today/bluetooth.html), but with some additional usability fixes and shortcuts in Chrome. Is that a generic web capability, potentially implemented by others as a thing separate from Bluetooth etc.? It looks for me it's too early to guess. But I might be totally wrong here.

**Comment by NOtherDev** [comment]
Moving Gamepad API to the separate issue: #39
The rest mentioned here is already handled somehow.
