### ISSUE TITLE
mobile SMS

### ISSUE THREAD

**Issue by quide** [NOtherDev/whatwebcando#29]
Hi,

Where is the test to check if web app can interface the mobile phone network capabilities in order e.g. to send SMS?
Is this possible? Will it be possible soon?

Cheers!

**Comment by NOtherDev** [comment]
No, this is not possible on the Web Platform and I don't think it will be available soon - at least I haven't heard of any plans or initiatives.
There was once [an API for Firefox OS](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/API/Mobile_Messaging_API), but that was never picked up by others, nor adopted as a standard.

I'd consider adding that information to the website during next update. Thanks!

**Comment by kenchris** [comment]
Chrome is working on some SMS number verification API.

Probably in the WICG

**Comment by kenchris** [comment]
https://discourse.wicg.io/t/proposal-sign-up-api-for-web/1844

**Comment by NOtherDev** [comment]
Here it is: [SMS](https://whatwebcando.today/sms.html)
