### ISSUE TITLE
Pointer Events API

### ISSUE THREAD

**Issue by patrickhlauke** [NOtherDev/whatwebcando#3]
I see that https://whatwebcando.today/touch.html does mention Pointer Events, but (as Firefox and Chrome are both actively working on implementations) it may perhaps be worth including the API itself here too? Additionally, it may be worth pointing to the official https://w3c.github.io/pointerevents/ spec for it, instead of https://msdn.microsoft.com/library/hh673557(v=vs.85).aspx

**Comment by NOtherDev** [comment]
I've changed the link and added the API, but I'll keep the issue open as it would also be nice to fix the usage graphs that rely on Touch Events API only at the moment and the Pointer Events API data is available on caniuse.com, too. I'll think about that.
