### ISSUE TITLE
Alarms?

### ISSUE THREAD

**Issue by glittle** [NOtherDev/whatwebcando#30]
Chrome has an API available to extensions that allow the system to invoke your code at specific times. Is anyone planning to add that for progressive web apps? If so, this should be added to the list of features...

**Comment by NOtherDev** [comment]
Thanks! Yes, I have it on my list of potential site additions. I'll add a note one day, while cleaning my backlog. 

The API's status is kind of stall, though. Something like Contacts API - was available for Firefox OS once and no other vendor really expressed any interest. It would serve as "what web can't do today", actually, and while there's nothing wrong with that per se, it's always nice to add positive things :)

**Comment by NOtherDev** [comment]
[Task Scheduling](https://whatwebcando.today/scheduler.html) added.

**Comment by boghyon** [comment]
On the [corresponding W3 page](https://www.w3.org/TR/task-scheduler/), it says

> This specification is being republished as a Working Group Note as an indication that it not being progressed further as a Recommendation track document.

And calling `ServiceWorkerRegistration.taskScheduler` returns `undefined` in Chrome 68.

I think /scheduler.html should be removed.

**Comment by NOtherDev** [comment]
Quote from the Task Scheduling page:

> The API is not implemented by any browser vendor as of the end of 2017 and no browser vendor seem to signal any interest.

So I feel this is covered correctly. The point of the website is to give a clear overview of the Web Platform possibilities and it also means showing what is **not** available.
