### ISSUE TITLE
"This debug view expired"

### ISSUE THREAD

**Issue by davidmaxwaterman** [NOtherDev/whatwebcando#32]
Is there some way to make it so the 'standalone mode' works long-term?

1. visit 'https://whatwebcando.today/'
2. locate 'bluetooth' and click on it
3. in the 'live demo' section, click on 'result'
4. in the right hand section that appears, click on 'in the standalone mode.'

-> codepen opens with a message, "This debug view expired".

**Comment by NOtherDev** [comment]
I've updated the links to Debug views throughout the website, thanks for noticing.
The only way to make it work long-term with CodePen is to upgrade to their Pro plan that I might need to do one day...

**Comment by davidmaxwaterman** [comment]
Thanks for that. As a matter of interest....why is the BT api not available on desktop browsers when it is available on phones? Know of any discussion/debate on that?

**Comment by NOtherDev** [comment]
I'm not sure. Here is what I found in [Implementation Status page](https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md):

> The chrome://flags/#enable-experimental-web-platform-features flag must be enabled on Linux and Windows. In Chrome OS, Android, and Mac, the GATT Communication API is available without any flag.

**Comment by davidmaxwaterman** [comment]
That works :) enables BT and NFC - well, on your web page anyway :) When I try the demo, I get a dialog asking to pair, with a spinner presumably trying to find BT devices...but nothing gets listed....such is experimental :) Thanks!

**Comment by davidmaxwaterman** [comment]
Great job, btw. Thanks for the site.
