### ISSUE TITLE
Missing "Checks" and/or "X"

### ISSUE THREAD

**Issue by Artmann** [NOtherDev/whatwebcando#4]
There is neither a checkmark or an X after `HOMESCREEN INSTALATION` or `POINT DEVICE ADAPTATION`.

I'm running Chrome 45 on Ubuntu 15.10 

![](http://i.imgur.com/ub4tkaP.png)

**Comment by NOtherDev** [comment]
Yes, that is true. It's because I couldn't find an easy way to check the
availability of these features from the code itself (i.e. through
JavaScript). Do you maybe know how to do that?
1 gru 2015 08:10 "Christoffer Artmann" <notifications@github.com>
napisał(a):

**Comment by Artmann** [comment]
Okey :)
I've haven't really used those features myself so I got no idea on how to
check for their availability.


2015-12-01 8:28 GMT+01:00 Adam Bar <notifications@github.com>:

**Comment by NOtherDev** [comment]
Fixed for Pointer Device Adaptation.
For Home Screen Installation currently [there's no way](https://twitter.com/NOtherDev/status/682302564952584192) to detect the support.
So there's nothing I can do here apart from UA sniffing and I don't want to do that - closing the issue.
