### ISSUE TITLE
Do a non js version

### ISSUE THREAD

**Issue by HumanG33k** [NOtherDev/whatwebcando#40]
Can you do a non js version for testing more browser.

**Comment by NOtherDev** [comment]
Not sure what do you mean. The site is functional without JavaScript (you can read and navigate). Obviously the dynamic parts does not work without JavaScript (feature detection, live demos, usage charts), but this is kind of expected when the majority of the features are JavaScript-based and there's no way to use it with JavaScript disabled. Let me know exactly what is the issue, please.

**Comment by NOtherDev** [comment]
Closing - no feedback. Feel free to reopen at any time.
