### ISSUE TITLE
Count how many  are available

### ISSUE THREAD

**Issue by HumanG33k** [NOtherDev/whatwebcando#41]
For a rapid comparison between browser can you add a count of available api.
Something like : 
Available :  12 / max

**Comment by NOtherDev** [comment]
I don't see a benefit of adding such a feature. It will clutter the home page. It will deepen the (already given) impression that the support of all the features is binary (either available or not, while the reality is more complex). It will suggest that the purpose of this website is to differentiate browsers to choose the worst and the best one while it is to show the capabilities of the Web platform as a whole, to show that every browser has the basic features available and potentially more. I'm against this idea - closing.
