### ISSUE TITLE
Web Share API

### ISSUE THREAD

**Issue by johnbillion** [NOtherDev/whatwebcando#42]
The [Web Share API is now available in Chrome for Android](https://developers.google.com/web/updates/2017/09/nic61). It would be neat to add this to the list of features on the site.

**Comment by NOtherDev** [comment]
Have a look at [Inter-App Communication](https://whatwebcando.today/app-communication.html) - I guess this is what you're looking for. Thank you!

**Comment by jimmywarting** [comment]
came here, and was going to suggest the same thing since i could not find it. maybe needs another title?
