### ISSUE TITLE
Recording Media example doesn't work in Firefox

### ISSUE THREAD

**Issue by autonome** [NOtherDev/whatwebcando#43]
It correctly says that Firefox supports the feature, but the video example doesn't actually work.

cc @atopal

**Comment by NOtherDev** [comment]
@autonome Thanks for the report. I've checked on Firefox 57 both on macOS and on Android and it works as expected - shows me the video, allows me to download it as webp and I'm able to view it after downloaded.
What is your setup?

**Comment by atopal** [comment]
I'm on Firefox 58 on MacOS, recoding and downloading works, but nothing is displayed on the page.

**Comment by NOtherDev** [comment]
Indeed. The demo code assumed co-existence of old `moz`-prefixed properties but FF 58 [have removed one of these](https://bugzilla.mozilla.org/show_bug.cgi?id=1183495). Fixed now (ensure your Service Worker gets the update).

**Comment by atopal** [comment]
Thanks, working great now 👍
