### ISSUE TITLE
About prompt twices

### ISSUE THREAD

**Issue by ronaldohoch** [NOtherDev/whatwebcando#49]
![image](https://user-images.githubusercontent.com/2287371/46095797-cc7e9080-c193-11e8-845f-64e8b66a9932.png)
Hello! I love and use this site in my technical lectures on PWA, but...

I didn't find where you prompt the user and why have two prompts on Android devices

**Comment by NOtherDev** [comment]
You're absolutely right, it's unnecessary. I created it when Chrome 68 was in early beta and had no mini-infobar idea implemented yet, so this was the only way to have the Add To Home Screen prompt triggered. Funny thing is I removed it literally few hours ago in commit https://github.com/NOtherDev/whatwebcando/commit/baa146fb2b98c2754509a60494b692fa576b1349. So now it's only a native prompt that is shown.

Thank you for the issue, please reopen if something isn't right there, still.
