### ISSUE TITLE
WebNFC API - things I've discovered which took hours to unravel

### ISSUE THREAD

**Issue by boatbodger** [NOtherDev/whatwebcando#55]
Two things: When using WebNFC, the namespace will only appear when the javascript is served via https://  If you try to put it in a web site URL starting http:// it is hidden.  It would be very helpful to have this mentioned in the "how to" part of NFC on this web page.

Also, in Chrome, the newer version (Canary, version 78) has renamed the facilities.  They are now NFCReader() and NFCWriter() at the top global level, not buried under navigator.nfc

Hope this saves some other folks a few hours of head-scratching

**Comment by NOtherDev** [comment]
Thanks, that's helpful! 
I'm planning to review all the content pretty soon, so I'll make sure this is included.
Will let you know!

**Comment by NOtherDev** [comment]
Included in the newest update from @beaufortfrancois - see [NFC](https://whatwebcando.today/nfc.html). Thanks @boatbodger.
