### ISSUE TITLE
Provide a TWA

### ISSUE THREAD

**Issue by mfranzke** [NOtherDev/whatwebcando#57]
I do love your website for doing research as well as trying out some of the web functionalities.

This works perfectly fine for a PWA, but there might be some more permissions / differences when using the website within a [TWA.](https://developers.google.com/web/updates/2019/08/twas-quickstart)

Could you please provide this one as well? I've actually even also found an Online TWA generator tool the latest, but cannot find the page in my history anymore ...

**Comment by NOtherDev** [comment]
I'm working on the large refresh of the project. It is definitely an interesting idea. Stay tuned 🙂

**Comment by mfranzke** [comment]
@NOtherDev, btw. do you need any support / helping hands on the refresh ?

**Comment by NOtherDev** [comment]
This is nice of you, @mfranzke. I'm nearly done, just need few proper hours to polish it and publish. But if you're willing to help, any content-side help is definitely welcome. For example, amongst others, the [Home Screen Installation](https://whatwebcando.today/installation.html) page definitely urges for TWA/PWA in the stores information.

**Comment by NOtherDev** [comment]
@mfranzke Here it is, finally: https://play.google.com/store/apps/details?id=today.whatwebcando.twa
