### ISSUE TITLE
permissions issue on android

### ISSUE THREAD

**Issue by aernan** [NOtherDev/whatwebcando#61]
To make the webnfc feature work on Android (chrome) you need to first enable webnfc. You can do that by typing "about:features" into chrome. Then searching for nfc. Once enabled you need to restart chrome. 
I then navigate to the demo page for webnfc. When I try a read I get a permissions pop up as expected. The trouble is the button does not accept input. I tried adding a bluetooth mouse to my S10+ and was able to actually depress the button but the prompt never closed.

**Comment by NOtherDev** [comment]
@beaufortfrancois Not sure is this something wrong with the demo or with the NFC impl itself? Thought you might be interested.

**Comment by aernan** [comment]
When I load the demo page on my laptop the NFC window.NDEFreader not supported. On Android(my phone) it shows up as supported after enabling webnfc.

**Comment by beaufortfrancois** [comment]
Web NFC is implemented only in Chrome for Android for now hence why `NDEFReader` objects does not exist on desktop platforms.

What do you mean by "The trouble is the button does not accept input."?
Can you share a screenshot?

Which version of Chrome do you use?
It's better to use [Chrome Canary](https://play.google.com/store/apps/details?id=com.chrome.canary&hl=en)

**Comment by aernan** [comment]
This permissions box pops up. When I try to press "Allow" it never presses.
I can't confirm the permission.

**Comment by beaufortfrancois** [comment]
Can you share a screenshot?

**Comment by aernan** [comment]
Yes. I tried replying to the email with the attachment but that did not work. How do I share the screenshot?

**Comment by beaufortfrancois** [comment]
Maybe https://imgur.com/?

**Comment by aernan** [comment]
https://imgur.com/ci0kV78 thanks that was good advice.

**Comment by aernan** [comment]
I installed chrome canary and repeated the steps. It works there. I guess
that chrome stable is not allowing it.

**Comment by NOtherDev** [comment]
@beaufortfrancois What's the status of WebNFC Origin Trial? I can see there is a new one, is the previous one expired? Shouldn't it still work on stable 79?

**Comment by beaufortfrancois** [comment]
The origin trial is meant to start in Chrome 81: https://developers.chrome.com/origintrials/#/view_trial/236438980436951041
There was no previous one.

**Comment by NOtherDev** [comment]
Oh my. Sorry, I must have mixed it up with some other.

As you figured the issue was about the expected browser support, I'm closing it. Thanks!
