### ISSUE TITLE
Contacts API -> Contact Picker API

### ISSUE THREAD

**Issue by leeoniya** [NOtherDev/whatwebcando#62]
@NOtherDev 

The Contact Picker API replaces the abandoned Contacts API

Currently it is supported in Chrome 80: https://web.dev/contact-picker/

Should be supported elsewhere soon:

https://github.com/WICG/contact-api
https://wicg.github.io/contact-api/spec/

**Comment by NOtherDev** [comment]
@leeoniya It is already described and demoed by [Contacts](https://whatwebcando.today/contacts.html) section. And I can see it green on Android.

**Comment by leeoniya** [comment]
ah, sorry. definitely missed it.
