### ISSUE TITLE
Proposal to add Project Fugu APIs

### ISSUE THREAD

**Issue by tomayac** [NOtherDev/whatwebcando#64]
Hi @NOtherDev 👋, 

Your site [whatwebcando.today](https://whatwebcando.today/) has become a primary destination for showing off, well, what the web can do today. Congratulations 🎉!

In [Project Fugu](https://web.dev/fugu-status/), we work on new browser capabilities that push the web platform forward.

May I propose [whatwebcando.today](https://whatwebcando.today/) to list them? Currently missing are:

- [Shape Detection](https://web.dev/shape-detection/) (for the time being, only barcode detection).
- [Badging](https://web.dev/badging-api/)
- [Content Indexing](https://web.dev/content-indexing-api/)
- [Native File System](https://web.dev/native-file-system/)
- [Notification Triggers](https://web.dev/notification-triggers/)
- [Web Serial](https://codelabs.developers.google.com/codelabs/web-serial/)
- [Web OTP](https://web.dev/sms-receiver-api-announcement/)
- [Async Clipboard](https://web.dev/image-support-for-async-clipboard/) (the image part)
- [Getting installed related apps](https://web.dev/get-installed-related-apps/)
- [Periodic Background Sync](https://web.dev/periodic-background-sync/)
- [Web Share](https://web.dev/web-share/) (including file share)
- [Web Share Target](https://web.dev/web-share-target/) (including receiving files)

Your site already does list (thanks!):
 
- [Wake Lock](https://web.dev/wakelock/)
- [Web NFC](https://web.dev/nfc/)

Thanks for your consideration!

Cheers,
Tom from the 🐡 Project Fugu team

**Comment by NOtherDev** [comment]
Thanks Tomas. 
I always had a bit different way of structuring the content. Instead of by API, I try to list it by high-level feature, so some of these new APIs for me would rather land within some existing features. 

Actually, in some cases they are already there:
* Web OTP is described in [SMS](https://whatwebcando.today/sms.html)
* Web Share & Web Share Target are described in [Inter-App Communication](https://whatwebcando.today/app-communication.html)

The rest clearly is on my roadmap, although it's always hard to find enough time 🙂
I'm open for cooperation in any form, though. Maybe you could contribute with some demos, for example?

**Comment by tomayac** [comment]
> I always had a bit different way of structuring the content. Instead of by API, I try to list it by high-level feature, so some of these new APIs for me would rather land within some existing features.

Fully understand, I wasn't proposing you change this :-) 

> Web OTP is described in SMS

The new Web OTP API actually wants to decouple the transport (currently SMS, but in the future, I don't know, WhatsApp or Signal or anything really) from the OTP retrieval. The current code uses `await navigator.credentials.get({otp: {transport: ["sms"]}});`.

> Web Share & Web Share Target are described in Inter-App Communication

Oh, I didn't see this, I scanned the homepage for "share". Maybe consider adding "share" to the section title?

> Maybe you could contribute with some demos, for example?

I have provided links to all APIs, there always is a demo. Does this help already?

**Comment by NOtherDev** [comment]
Status update & plans for the items:

* [ ] **Shape Detection** -> new feature
* [ ] **Badging** -> probably will go to [Home Screen Installation](https://whatwebcando.today/installation.html)
* [ ] **Content Indexing** -> not sure, either separate feature or to [Offline Mode](https://whatwebcando.today/offline.html)?
* [ ] **Native File System** -> update to [File Access](https://whatwebcando.today/files.html)
* [ ] **Notification Triggers** -> will go to [Task Scheduling](https://whatwebcando.today/scheduler.html)
* [ ] **Web Serial** -> new feature
* [ ] **Web OTP** -> will go to [Credentials](https://whatwebcando.today/credentials.html)?
* [ ] **Async Clipboard (the image part)** -> update to [Clipboard](https://whatwebcando.today/clipboard.html)
* [ ] **Getting installed related apps** -> not sure if this fits in scope of showcasing what the web can do in contrast to native
* [x] **Periodic Background Sync** -> added to [Task Scheduling](https://whatwebcando.today/scheduler.html)
* [x] **Web Share** -> already in Inter-App Sharing (note the name change)
* [x] **Web Share Target** -> as above

**Comment by tomayac** [comment]
Thanks for sharing the detailed plan! Sounds great to me!

**Comment by NOtherDev** [comment]
Completed. Thanks @tomayac for providing me a motivation!

**Comment by tomayac** [comment]
Brilliant, thanks so much for working on this. I have mentioned this yesterday in the Project Fugu prioritization meeting. Here's the agenda item:

<img width="525" alt="Screen Shot 2020-04-23 at 11 29 51" src="https://user-images.githubusercontent.com/145676/80083371-d3c77500-8555-11ea-871d-6a689e4d6738.png">
