### ISSUE TITLE
npm start gives error

### ISSUE THREAD

**Issue by omscse** [NOtherDev/whatwebcando#65]
Am I missing something?

npm run start
----------------

(node:8336) ExperimentalWarning: The ESM module loader is experimental.
Starting server on port 3000
file:///C:/Data/Web%20RTC/whatwebcando-master/whatwebcando/__sapper__/build/index.js:6
require('./server/server.js');
^

ReferenceError: require is not defined
    at file:///C:/Data/Web%20RTC/whatwebcando-master/whatwebcando/__sapper__/build/index.js:6:1
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:176:24)
npm ERR! code ELIFECYCLE

npm run dev
---------------

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Data\Web RTC\whatwebcando-master\whatwebcando\__sapper__\dev\server\server.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1172:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)

**Comment by NOtherDev** [comment]
Yes, it is broken in Node v13, it works on Node v10, though.
I didn't bother to check what's the problem, to be honest. Any hints welcome :)

**Comment by omscse** [comment]
Sure.  Thank you for quick response. This project is really a great work!
