### ISSUE TITLE
Native File System API exeption

### ISSUE THREAD

**Issue by SuperPat45** [NOtherDev/whatwebcando#67]
The Latest chrome throw an exception clicking button "Choose file to create or overwrite (Native File System API)" :
> VM33:38 Uncaught (in promise) TypeError: Failed to execute 'chooseFileSystemEntries' on 'Window': The provided value 'saveFile' is not a valid enum value of type ChooseFileSystemEntriesType.
>     at writeFile (<anonymous>:38:31)
>     at HTMLButtonElement.onclick (files.html:1)

It seems that the old trial value :
```
  const handle = await window.chooseFileSystemEntries({
    type: 'saveFile',
  });
```
should be changed to:
```
  const handle = await window.chooseFileSystemEntries({
    type: 'save-file',
  });
```

**Comment by NOtherDev** [comment]
Fixed by #68.
