### ISSUE TITLE
NFC Write

### ISSUE THREAD

**Issue by nielsq** [NOtherDev/whatwebcando#76]
There is in issue with writing NFC tags.
`async function writeTag() {
  if ("NDEFReader" in window) {
    const ndef = new NDEFReader();`
needs to be
`async function writeTag() {
  if ("NDEFReader" in window) {
    const ndef = new NDEFWriter();`

**Comment by NOtherDev** [comment]
Hi @nielsq. Thanks for your issue. Your suggestion is not correct, though, `NDEFWriter` was merged into `NDEFReader` and removed both from [the spec](https://w3c.github.io/web-nfc/) as well as from Chromium implementation some time ago.
