### ISSUE TITLE
intents(?)

### ISSUE THREAD

**Issue by davidmaxwaterman** [NOtherDev/whatwebcando#8]
I noticed that 'Facebook' didn't appear in native apps' 'share' page when I used Facebook's web app (link on home screen), while it does if I use the native app. I asked around and it seems there's currently no way for a web app to make itself appear in such lists.

Is this something called 'intents'? It's been a while since I did native android development.

**Comment by NOtherDev** [comment]
I guess you're right, it was supposed to be handled by [Web Intents](http://webintents.org/), but is [no longer supported](https://developer.chrome.com/apps/app_intents) and it seems that [no real replacement is available](http://webmasters.stackexchange.com/questions/59395/what-is-the-replacement-for-the-web-intents-html-standard?newreg=24ae3d0f18924669bd6e38bb3ffed5e7), sadly. I'll maybe add that to the features list one day just to show that the web clearly can't do that today.

**Comment by davidmaxwaterman** [comment]
yeah, I ended up going back to the native facebook app because this feature is missing...I think it's kind of a big deal, at least while web apps are trying 'catch up' to native :/

**Comment by malyw** [comment]
There is Web Share API which is coming to Google: https://developers.google.com/web/updates/2016/10/navigator-share
It currently, works in Chrome on Android under the [Origin Trial](https://github.com/jpchase/OriginTrials/blob/gh-pages/developer-guide.md)

**Comment by NOtherDev** [comment]
Well, actually, I have added [Inter-App Communication](https://whatwebcando.today/app-communication.html) to What Web Can Do few months back. It includes the description of the new Web Share API as well as now defunct Web Intents. I just forgot to mention it in this issue :)
