### ISSUE TITLE
Task Scheduling is not available in PWA

### ISSUE THREAD

**Issue by Adrish-m** [NOtherDev/whatwebcando#96]
In this [link](https://whatwebcando.today/scheduler.html) (https://whatwebcando.today/scheduler.html) It is said that we can use Notification Trigger But it is abandoned and Periodic Sync is not perfect for that job so to be fair  I think PWAs can't do Task Scheduling.

**Comment by NOtherDev** [comment]
Thanks @Adrish-m for reaching out. All what you said is mentioned in the article and the support table states what the current browser allows - in Chrome's case it's clear that Notification Trigger isn't available.
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/1309057/159855084-a0352e70-e7c3-45fe-8b65-a5ede49b63f7.png">
Please reopen and propose a PR if you think this section should be improved - [here](https://github.com/NOtherDev/whatwebcando/blob/master/src/data/features/scheduler.js) is the appropriate file.
